config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tweets
  resources :connections


  post '/users/:followed_id/follow', to: 'connections#create', as: 'follow_user'
  post '/users/:followed_id/unfollow', to: 'connections#destroy', as: 'unfollow_user'

  root to: 'tweets#feed', as: 'home'

  get '/feed', to: 'tweets#all',format: :json, as: 'show_feed'

  get 'users/profile/:id', to: 'tweets#user', as: 'show_user_tweets'
  get 'users/followers', to: 'users#followers', as: 'show_followers'
  get 'users/following', to: 'users#following', as: 'show_following'
  get 'users/everyone', to: 'users#everyone', as: 'show_everyone'

  get "*a", to: "application#error_page", as: 'error_page'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/connection.rb
class Connection < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user, :class_name => "User", :foreign_key => "user_id"
  default_scope -> { order(created_at: :desc) }
  validates :message, presence: true, length: { maximum: 140 }
  validates :user_id, presence: true
  self.per_page = 100
end

app/models/user.rb
class User < ApplicationRecord
  devise :ldap_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tweets, dependent: :destroy
  has_many :connections, foreign_key: 'follower_id', dependent: :destroy
  has_many :inverse_connections, foreign_key: 'followed_id', class_name: 'Connection', dependent: :destroy
  has_many :following, through: :connections, source: :followed, class_name: 'User'
  has_many :followers, through: :inverse_connections, source: :follower, class_name: 'User'

  def following?(other_user)
    connections.find_by(followed_id: other_user.id)
  end

  def follow!(other_user)
    connections.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    connections.find_by(followed_id: other_user.id).destroy
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from DeviseLdapAuthenticatable::LdapException do |exception|
    render :text => exception, :status => 500
  end
  protect_from_forgery with: :exception

  before_filter :authenticate_user!
end

app/controllers/connections_controller.rb
class ConnectionsController < ApplicationController
    skip_before_filter :verify_authenticity_token, :only => :create

    def new
      current_user.follow!(User.find(connection_params[:followed_id]))
    end

    def create
      respond_to do |format|
        followed_user = User.find(connection_params[:followed_id])
        if current_user.follow!(followed_user)
          format.html { redirect_to :back, notice: "Following #{followed_user.email} now" }
        else
          format.html { redirect_to :back, notice: 'Failed to start following'}
        end
      end
    end

    def destroy
      @connection = Connection.find_by(follower_id: current_user.id, followed_id: connection_params[:followed_id] )
      @connection.destroy
      respond_to do |format|
        format.html { redirect_to :back, notice: 'Stopped following' }
      end
    end

    private

    def connection_params
      params.permit(:followed_id, :_method, :authenticity_token)
    end
end

app/controllers/tweets_controller.rb
require 'will_paginate/array'
class TweetsController < ApplicationController
  skip_before_filter :verify_authenticity_token, :only => [:create]
  skip_before_filter :authenticate_user!, :only => :all

  def feed
    respond_to do |format|
      @target_user = User.find(current_user.id)
      @tweets = feed_for(@target_user).paginate(:page => params[:page], :per_page => 100)
      format.json do
        render json: @tweets
      end

      format.html do
        render :feed
      end
    end
  end

  def user
    @target_user = User.find(params[:id])
    @tweets = @target_user.tweets.paginate(:page => params[:page], :per_page => 100)
    @user_feed = true
    render :feed
  end

  def all
    @tweets = Tweet.all
     render json: @tweets[0..100]
  end

  def new
    @tweet = Tweet.new(user_id: current_user.id)
  end

  def create
    @tweet = current_user.tweets.build(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to :back, notice: 'Tweeted' }
        format.json { redirect_to :back, notice: 'Tweeted'}
      else
        format.html { redirect_to :back, notice: 'Failed to Tweet'}
        format.json { redirect_to :back, notice: 'Failed to Tweet'}
      end
    end
  end

  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Tweet deleted.' }
      format.json { head :no_content }
    end
  end

  private

    def tweet_params
      params.permit(:message)
    end

    def feed_for(user)
      feed = []
      user.following.each { |following| feed.concat(following.tweets) }
      feed
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def followers
    @users = current_user.followers
  end

  def following
    @users = current_user.following
  end

  def everyone
    @users = User.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/connections_helper.rb
module ConnectionsHelper
end

app/helpers/feed_helper.rb
module FeedHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/error_page.html.erb
<% flash[:notice]="YOU ARE TRYING TO ACCESS AN INVALID PAGE" %>
<div class="well well-sm center-block text-center"><h1>HAVE FUN !!!</h1>
  <%= link_to 'Home', home_path, :class => "btn btn-primary block-center"%>
</div>

app/views/application/navbar_logged_in.html.erb
<ul class="nav nav-tabs navbar-fixed-bottom navbar-inverse container-fluid">
  <li role="presentation"><a href="/">Home</a></li>
  <li role="presentation"><a href="/users/profile/<%= current_user.id %>">Profile</a></li>
  <li role="presentation"><a href="/users/followers">Followers</a></li>
  <li role="presentation"><a href="/users/following">Following</a></li>
  <li role="presentation"><a href="/users/everyone">All</a></li>
  <li role="presentation"><a href="/users/sign_out" data-method="delete">Logout</a></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Craft Demo</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= bootstrap_flash %>
    <%= yield %>
  </body>
</html>

app/views/tweets/_tweet.html.erb
<li>
  <div class="avatar">
    <a href="<%=show_user_tweets_path(tweet.user.id)%>"><img src="http://www.croop.cl/UI/twitter/images/doug.jpg"></a>
    <div class="hover">
      <div class="icon-twitter"></div>
    </div>
  </div>
  <div class="bubble-container">
    <span><p style="color: #2084c7"><strong><small><a href="<%=show_user_tweets_path(tweet.user.id)%>">@<%= tweet.user.email %></a></small></strong></p>
    <p style="word-wrap: break-word; color: #999999">Posted <%= time_ago_in_words(tweet.created_at) %> ago</p></span>
    <div class="bubble">
      <p style="word-wrap: break-word;"><%= tweet.message %></p>
      <div class="over-bubble">
        <div class="icon-mail-reply action"></div>
        <div class="icon-retweet action"></div>
        <div class="icon-star"></div>
      </div>
    </div>
    <br/>

    <div class="arrow"></div>
  </div>
</li>

app/views/tweets/feed.html.erb
<div class="container-fluid well">
  <div class="col-lg-4">
    <%= render @target_user %>
  </div>
  <div class="col-lg-8">
    <div class="panel panel-success">
      <div class="panel-body">
        <span class="first">
          <% if @target_user.id == current_user.id %>
              <% if @user_feed %>
                  My Tweets
              <% else %>
                  My Feed
              <% end %>
           <% else %>
              <%= @target_user.email %>
           <% end %>
			    <span class="icon-edit new"></span>
        </span>
        <ul style="list-style: none;" class="timeline">
            <%= render @tweets %>
        </ul>
      </div>
    </div>
  </div>
</div>
<%= will_paginate @tweets %>

<%= render template: 'application/navbar_logged_in' %>

app/views/tweets/feed.js.erb
$('#feed').append('<%= escape_javascript render(@tweets) %>');
$('.pagination').replaceWith('<%= escape_javascript will_paginate(@tweets) %>');

app/views/tweets/index.html.erb
<div class="container-fluid well">
  <div class="col-lg-8">
    <div class="panel panel-success">
      <div class="panel-body">
        <span class="first">
            All Tweets
          <span class="icon-edit new"></span>
        </span>
        <ul style="list-style: none;" class="timeline">
          <%= render @tweets %>
        </ul>
      </div>
    </div>
  </div>
</div>
<%= will_paginate @tweets %>

<%= render template: 'application/navbar_logged_in' %>

app/views/users/_user.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><strong><%= user.email%></strong></h3>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="btn-pref btn-group btn-group-justified btn-group-lg col-sm-4" role="group" aria-label="...">
        <div class="btn-group" role="group">
          <button type="button" id="stars" class="btn btn-primary" onclick="location.href='<%= show_user_tweets_path(user.id) %>'" data-toggle="tab"><span class="glyphicon glyphicon-star" aria-hidden="true"></span>
            <div class="hidden-xs">Tweets done: <%= user.tweets.size %></div>
          </button>
        </div>
        <div class="btn-group" role="group">
          <button type="button" id="followers" class="btn btn-default"
                  <% if current_user.id == user.id %>
                  onclick="location.href='<%= show_followers_path%>'"
                  <%end %>
                  href="#tab2" data-toggle="tab"><span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
            <div class="hidden-xs">Followers: <%= user.followers.size %></div>
          </button>
        </div>
        <div class="btn-group" role="group">
          <button type="button" id="following" class="btn btn-default"
                  <% if current_user.id == user.id %>
                  onclick="location.href='<%= show_following_path%>'"
                  <%end %>
                  href="#tab3" data-toggle="tab"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>
            <div class="hidden-xs">Following: <%= user.following.size %></div>
          </button>
        </div>
      </div>
    </div>
    <br/>
    <% if current_user.id == user.id %>
        <div class="row">
          <div class="col-md-4" style="padding-bottom:0">
            <form accept-charset="UTF-8" action="/tweets" method="POST">
                  <textarea class="field tweetbox" id="message" name="message"
                            placeholder="Type in your message" rows="5" cols="59"></textarea>
              <button class="btn btn-info" type="submit">Post Tweet</button>
            </form>
          </div>
        </div>
    <% end %>
  </div>
  <% if current_user.id == user.id %>
      <div class="panel-footer"><%= link_to('Logout', destroy_user_session_path, :method => :delete, class: 'btn btn-info') %> </div>
  <% else %>
      <% if current_user.following? user %>
          <div class="panel-footer"><%= link_to('Unfollow', unfollow_user_path(user.id), :method => :post, class: 'btn btn-error') %> </div>
      <% else %>
          <div class="panel-footer"><%= link_to('Follow', follow_user_path(user.id), :method => :post, class: 'btn btn-info') %> </div>
      <%end%>
  <% end %>
</div>

app/views/users/everyone.html.erb
<div class="bubble-container">
  <div class="col-lg-6">
    <h2>All Users</h2>
    <%= render @users %>
  </div>
</div>
<%= render template: 'application/navbar_logged_in' %>

app/views/users/followers.html.erb
<div class="bubble-container">
  <div class="col-lg-6">
    <h2>People following you</h2>
    <%= render @users %>
  </div>
</div>
<%= render template: 'application/navbar_logged_in' %>

app/views/users/following.html.erb
<div class="bubble-container">
  <div class="col-lg-6">
    <h2>People you are following</h2>
    <%= render @users %>
  </div>
</div>
<%= render template: 'application/navbar_logged_in' %>